#include "colors.h"

// clang-format off
#define RGB333(r, g, b) (uint16_t)( \
    (((((unsigned int)(r) * 256 / 36) + 128) / 256) << 6) | \
    (((((unsigned int)(g) * 256 / 36) + 128) / 256) << 3) | \
    ((((unsigned int)(b) * 256 / 36) + 128) / 256) \
)

#define COLOR_BLACK     RGB333(0x00, 0x00, 0x00)
#define COLOR_BLUE      RGB333(0x00, 0x00, 0xAA)
#define COLOR_GREEN     RGB333(0x00, 0xAA, 0x00)
#define COLOR_CYAN      RGB333(0x00, 0xAA, 0xAA)
#define COLOR_RED       RGB333(0xAA, 0x00, 0x00)
#define COLOR_MAGENTA   RGB333(0xAA, 0x00, 0xAA)
#define COLOR_BROWN     RGB333(0xAA, 0x55, 0x00)
#define COLOR_GRAY      RGB333(0xAA, 0xAA, 0xAA)
#define COLOR_D_GRAY    RGB333(0x55, 0x55, 0x55)
#define COLOR_H_BLUE    RGB333(0x00, 0x00, 0xFF)
#define COLOR_H_GREEN   RGB333(0x00, 0xFF, 0x00)
#define COLOR_H_CYAN    RGB333(0x00, 0xFF, 0xFF)
#define COLOR_H_RED     RGB333(0xFF, 0x00, 0x00)
#define COLOR_H_MAGENTA RGB333(0xFF, 0x00, 0xFF)
#define COLOR_YELLOW    RGB333(0xFF, 0xFF, 0x00)
#define COLOR_WHITE     RGB333(0xFF, 0xFF, 0xFF)

#define COLOR_MONO_AMBER_BG  RGB333(0x12, 0x12, 0x00)
#define COLOR_MONO_AMBER_FG  RGB333(0xff, 0xb0, 0x00)
#define COLOR_MONO_GREEN_BG  RGB333(0x00, 0x12, 0x00)
#define COLOR_MONO_GREEN_FG  RGB333(0x33, 0xff, 0x33)
// clang-format on


// This is the color palette generated by NTSC artifact color when shifted out LSB -> MSB
// and phase-synchronized with the color reference signal.
//
// Ref: Understanding the Apple II, page 8-24, or Understanding the Apple IIe, page 8-39
const uint16_t ntsc_palette[16] = {
 COLOR_BLACK,
 COLOR_BLUE,
 COLOR_GREEN,
 COLOR_CYAN,
 COLOR_RED,
 COLOR_MAGENTA,
 COLOR_BROWN,
 COLOR_GRAY,
 COLOR_D_GRAY,
 COLOR_H_BLUE,
 COLOR_H_GREEN,
 COLOR_H_CYAN,
 COLOR_H_RED,
 COLOR_H_MAGENTA,
 COLOR_YELLOW,
 COLOR_WHITE
};
